version: '3'
services:
  angular-ui:
    build:
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: angular-ui
    volumes:
       - ./app-ui:/usr/src/app/app-ui
       - /usr/src/app/app-ui/node_modules